### ISSUE TITLE
Failed to publish CNAMEs: too many objects

### ISSUE THREAD

**Issue by operutka** [grishy/go-avahi-cname#13]
I'm getting the following error after some time (around 3 days):
```
Jan 27 17:59:22 ha go-avahi-cname[670]: 2024/01/27 17:59:22 Publishing every 300s and CNAME TTL 600s
Jan 31 07:19:22 ha go-avahi-cname[670]: Error:
Jan 31 07:19:22 ha go-avahi-cname[670]:  > failed to publish CNAMEs: failed to create entry group: Too many objects
```

The avahi daemon reports the same thing:
```
Jan 31 07:19:22 ha avahi-daemon[642]: Too many objects for client ':1.7', client request failed.
```

The service is being run on Ubuntu 22.04 using systemd. Though I guess it isn't really that important. I'm using the following command:
```bash
/usr/bin/go-avahi-cname cname grafana.local.
```

**Comment by operutka** [comment]
I forgot to add the command I'm using:
```bash
/usr/bin/go-avahi-cname cname grafana.local.
```

**Comment by grishy** [comment]
I wonder if the message is issued from avahi on a request to create an object. Does this happen intermittently or does it happen and then cname does not work after it?

**Comment by grishy** [comment]
I've also found that `subdomain` works better, so if you have the option to switch, I suggest it.

**Comment by grishy** [comment]
Save for later same issues
- https://github.com/davesteele/comitup/issues/77
- https://bugzilla.redhat.com/show_bug.cgi?id=1190477

**Comment by grishy** [comment]
Supposedly, I've found why it doesn't work properly.   
I think I wasn't using `EntryGroup` in the most efficient way. I need to reuse one and not create one every time.

**Comment by grishy** [comment]
Try [v2.0.4](https://github.com/grishy/go-avahi-cname/tree/v2.0.4)

**Comment by grishy** [comment]
@operutka ping me is it working or not :)
For me OK

**Comment by operutka** [comment]
Thanks. I'll test the fix next week. I've also tried using `subdomain` but it does not work for some reason. If I'm using `subdomain`, clients can't resolve subdomain addresses. They always end up with `SERVFAIL` regardless if go-avahi-cname is actually running or not.

**Comment by grishy** [comment]
Oh, can you create issue about it also?

**Comment by operutka** [comment]
I've tested the fix. It's been running stable more than a week, so I think it's fixed.
