### ISSUE TITLE
using avahi with IPv6

### ISSUE THREAD

**Issue by alefcarlos** [grishy/go-avahi-cname#18]
Hey! It an awesome project!

I'm using it with https://cosmos-cloud.io/ to selfhost my own private cloud on  an Ubuntu 24 LTS Server

My hostname is *homelab* and it is resolved as `homelab.local`:

```
PS C:\Users\anunes> ping homelab.local

Disparando homelab.local [2804:14d:7880:82bf:8232:53ff:fe05:45c9] com 32 bytes de dados:
Resposta de 2804:14d:7880:82bf:8232:53ff:fe05:45c9: tempo=100ms
Resposta de 2804:14d:7880:82bf:8232:53ff:fe05:45c9: tempo=104ms
Resposta de 2804:14d:7880:82bf:8232:53ff:fe05:45c9: tempo=101ms
Resposta de 2804:14d:7880:82bf:8232:53ff:fe05:45c9: tempo=122ms

Estatísticas do Ping para 2804:14d:7880:82bf:8232:53ff:fe05:45c9:
    Pacotes: Enviados = 4, Recebidos = 4, Perdidos = 0 (0% de
             perda),
Aproximar um número redondo de vezes em milissegundos:
    Mínimo = 100ms, Máximo = 122ms, Média = 106ms
```

I can browse to http://homelab.local as expected

I'm running go-avahi-cname using docker:

```
 docker run --network host --privileged --name avahi-cname -h avahi-cname --restart=always -v /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket ghcr.io/grishy/go-avahi-cname:v2.0.5
```

and the outputlog:

```
2024/09/15 16:11:35 Creating publisher
2024/09/15 16:11:35 Getting FQDN from Avahi
2024/09/15 16:11:35 FQDN: homelab.local.
2024/09/15 16:11:35 Create connection to multicast
2024/09/15 16:11:35 Start listening
2024/09/15 16:40:13 Creating publisher
2024/09/15 16:40:13 Getting FQDN from Avahi
2024/09/15 16:40:13 FQDN: homelab.local.
2024/09/15 16:40:13 Create connection to multicast
2024/09/15 16:40:13 Start listening
```

And i tried to browse to http://test.homelab.local and it cant be resolved. Is there any log that I can consume to try to find out the problem ?

**Comment by grishy** [comment]
Hi @alefcarlos 
There may be an issue with IPv6; I didn't check, so some may exist.
Can you check with Avahi IPv4 only mode?
I remember that you need to change 2 parameters:
- `use_ipv6` - no
- `aaaa records` - no

^above I wrote from my memory, check before in official docs if possible 🙂
I'm sick right now and I'll check IPv6 later if I think about it 🤒

**Comment by alefcarlos** [comment]
@grishy, you were on fire!

The configs are:

use-ipv4=yes
use-ipv6=no
publish-aaaa-on-ipv4=no

And then restart de deamon, and the resolution is ok!

Thank you very much.

I'm gonna change the issue title to help others ;)
